title: <p align="center"> Ngu Huu Kien </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/HuuKienIT">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing Engineer degree in Software Engineer at Sai Gon University.
  <br><br>
  Passionate about DevOps, I aim to streamline software development
              through automation and collaboration. Skilled in cloud
              infrastructure, Docker, Kubernetes, and Ansible, I'm committed to
              optimizing workflows for enhanced efficiency and scalability.
              Eager to contribute to dynamic teams and drive innovation in
              fast-paced environments.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
